[package]
name = "fast_toml"
version = "0.2.0"
edition = "2021"
authors = ["Guilherme Carreiro <karreiro@gmail.com>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = "0.6.4"
toml = "0.8.13"
